version: '3'
services:
  nginxweb:
    container_name: prod-nginx
    image: nginx:1.14
    # build: ./
    restart: always
    ports:
      - 80:80
    volumes:
      - /data/html:/usr/share/nginx/html
